"""
USER PLAYBOOK PARAMS - DEFINED AS CONFIG PARAMETERS ON APPS
IN USE WITH "User Playbooks"
"""

# user playbook script details
REPO_URL_PARAM = "REPO_URL"
REPO_USERNAME_PARAM = "REPO_USERNAME"
REPO_PASSWORD_PARAM = "REPO_PASSWORD"

# user playbook settings
INVENTORY_GROUPS_PARAM = "INVENTORY_GROUPS"
CONNECTION_METHOD_PARAM = "CONNECTION_METHOD"
CONNECTION_SECURED_PARAM = "CONNECTION_SECURED"
ACCESS_KEY_PARAM = "ACCESS_KEY"
