"""
HOST OVERRIDE PARAMS - IF PRESENT ON RESOURCE THEY WILL OVERRIDE THE SERVICE DEFAULT
TO BE CREATED IN SYSTEM AS GLOBAL ATTRIBUTE
"""
ACCESS_KEY_ATTR = "Access Key"
CONNECTION_METHOD_ATTR = "Connection Method"
SCRIPT_PARAMS_ATTR = "Script Parameters"
INVENTORY_GROUP_ATTR = "Inventory Groups"
CONNECTION_SECURED_ATTR = "Connection Secured"
